{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "helm.fullname" . }}-migration-job"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 20
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 3600
  parallelism: 1
  completions: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Values.saname }}
      volumes:
        - name: my-api-token
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.saname }}-aws-secrets
      restartPolicy: 'OnFailure'
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret.name }}
      containers:
      - name: init
        image: {{ .Values.migrationJob.repository }}:{{ .Values.migrationJob.tag }}
        imagePullPolicy: {{ .Values.migrationJob.pullPolicy }}
        resources:
{{ toYaml .Values.migrationJob.resources | indent 10 }}
        command: ["/bin/sh", "-c"]
        args: ["cd packages/migrations; npm run db:migrate"]
        volumeMounts:
          - name: my-api-token
            mountPath: /mnt/api-token
            readOnly: true
        env:
          - name: AUTHENTICATION_SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: AUTHENTICATION_SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: AUTHENTICATION_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: AUTHENTICATION_SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: AUTHENTICATION_SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: AUTHENTICATION_SERVICE_DB_DATABASE
          - name: AUDIT_SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: AUDIT_SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: AUDIT_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: AUDIT_SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: AUDIT_SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: AUDIT_SERVICE_DB_DATABASE
          - name: NOTIFICATION-SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: NOTIFICATION-SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: NOTIFICATION-SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: NOTIFICATION-SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: NOTIFICATION-SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: NOTIFICATION-SERVICE_DB_DATABASE
          - name: SCHEDULER-SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: SCHEDULER-SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: SCHEDULER-SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: SCHEDULER-SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: SCHEDULER-SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: SCHEDULER-SERVICE_DB_DATABASE
          - name: VIDEO-CONFERENCING-SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: VIDEO-CONFERENCING-SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: VIDEO-CONFERENCING-SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: VIDEO-CONFERENCING-SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: VIDEO-CONFERENCING-SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: VIDEO-CONFERENCING-SERVICE_DB_DATABASE
          - name: USER-TENANT-SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: USER-TENANT-SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: USER-TENANT-SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: USER-TENANT-SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: USER-TENANT-SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: USER-TENANT-SERVICE_DB_DATABASE
          
          - name: PRODUCT_SERVICE_DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_HOST
          - name: PRODUCT_SERVICE_DB_PORT
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PORT
          - name: PRODUCT_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_USER
          - name: PRODUCT_SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-token
                key: DB_PASSWORD
          - name: PRODUCT_SERVICE_DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-token
                key: PRODUCT_SERVICE_DB_DATABASE
          
          - name: TENANT_NAME
            value: {{ .Values.tenantName }}
          - name: TENANT_KEY
            value: {{ .Values.tenantKey }}
          - name: TENANT_SECRET
            value: {{ .Values.tenantSecret }}
          - name: TENANT_EMAIL
            value: {{ .Values.tenantEmail }}
          - name: TENANT_CLIENT_ID
            value: {{ .Values.clientId }}
          - name: TENANT_CLIENT_SECRET
            value: {{ .Values.publicKey }}
          - name: ADMIN_USER_TENANT_ID
            value: {{ .Values.adminUserTenantId }}
          - name: REDIRECT_URL
            value: "https://{{ .Values.hostname }}/{{ .Values.frontend.home_path }}"
          - name: USERNAME
            value: {{ .Values.cognitoUser }}
          - name: USER_SUB
            value: {{ .Values.cognitoSub }}
{{- end }}