{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-cm-audit-service
  labels:
    app: {{ include "helm.fullname" . }}
data:
      PORT: '{{ .Values.auditService.port }}'
      NODE_ENV: '{{ .Values.auditService.node_env }}'
      LOG_LEVEL: '{{ .Values.auditService.log_level }}'
      BASE_PATH: '{{ .Values.auditService.base_path }}'
{{- end}}