{{- if .Values.subscriptionService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-cm-subscription-service
  labels:
    app: {{ include "helm.fullname" . }}
data:
      PORT: '{{ .Values.subscriptionService.port }}'
      NODE_ENV: '{{ .Values.subscriptionService.node_env }}'
      LOG_LEVEL: '{{ .Values.subscriptionService.log_level }}'
      BASE_PATH: '{{ .Values.subscriptionService.base_path }}'
      SITE: '{{ .Values.subscriptionService.site }}'
      API_KEY: '{{ .Values.subscriptionService.api_key }}'
      PAYMENT_GATEWAY_ID: '{{ .Values.subscriptionService.payment_gateway_id }}'
      WEBHOOK_USERNAME: '{{ .Values.tenantMgmtFacade.webhook_user }}'
      WEBHOOK_PASSWORD: '{{ .Values.tenantMgmtFacade.webhook_password }}'
{{- end}}