{{- if .Values.tenantMgmtFacade.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-cm-tenant-mgmt-facade
  labels:
    app: {{ include "helm.fullname" . }}
data:
      PORT: '{{ .Values.tenantMgmtFacade.port }}'
      NODE_ENV: '{{ .Values.tenantMgmtFacade.node_env }}'
      LOG_LEVEL: '{{ .Values.tenantMgmtFacade.log_level }}'
      BASE_PATH: '{{ .Values.tenantMgmtFacade.base_path }}'
      CSP_SCRIPT_SRC_HASH: '{{ .Values.tenantMgmtFacade.csp_script_src_hash }}'
      FROM_EMAIL: '{{ .Values.tenantMgmtFacade.from_email }}'
      NOTIFICATION_SERVICE_URL: 'https://{{ .Values.controlPlaneHost }}/notification-service'
      SUBSCRIPTION_SERVICE_URL: 'https://{{ .Values.controlPlaneHost }}/subscription-service'
      TENANT_MGMT_URL: 'https://{{ .Values.controlPlaneHost }}/tenant-mgmt-service'
      APP_VALIDATE_URL: 'https://{{ .Values.controlPlaneHost }}/tenant/add-tenant'
      APP_NAME: '{{ .Values.tenantKey}}'
      GATEWAY_ACCOUNT_ID: '{{ .Values.tenantMgmtFacade.gateway_id }}'
      WEBHOOK_USERNAME: '{{ .Values.tenantMgmtFacade.webhook_user }}'
      WEBHOOK_PASSWORD: '{{ .Values.tenantMgmtFacade.webhook_password }}'
      AUTH0_DOMAIN: '{{ .Values.tenantMgmtService.auth0_domain }}'
      AUTH0_CLIENT_ID: '{{ .Values.tenantMgmtService.auth0_client_id }}'
      KEYCLOAK_HOST: 'https://keycloak.{{ .Values.domain }}'
      KEYCLOAK_ADMIN_USERNAME: '{{ .Values.keycloakUser }}'
      AWS_REGION: '{{ .Values.region }}'
      DOMAIN_NAME: '{{ .Values.domain }}'
      NAMESPACE: '{{ .Values.projectName }}'
      ENVIRONMENT: '{{ .Values.environment }}'
      AWS_SES_SMTP_HOST: 'email-smtp.{{ .Values.region }}.amazonaws.com'
      AWS_SES_SMTP_PORT: '{{ .Values.notificationService.smtp_port }}'
      SMTP_FROM_EMAIL: '{{ .Values.tenantMgmtService.from_email }}'
      SMTP_FROM_DISPLAY_NAME: '{{ .Values.notificationService.smtp_display_name }}'
      STRIPE_SECRET: 'sk_test_51Pab3LKxH99wEJoTKBIoEWMdmTBXdtGCfGLmbrwvtSY7BBh140V0K5jgwcpiZwjkJfybK4RIx5rPeuK54J7CUgXJ00r0XUMPsj'
{{- end}}
