apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: http-check
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    containers:
      - name: main
        image: kuberhealthy/http-check:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_URL
            value: "https://{{ .Values.controlPlaneHost }}/"
          - name: COUNT
            value: "5"
          - name: SECONDS
            value: "1"
          - name: REQUEST_TYPE
            value: "GET"
          - name: PASSING
            value: "80"