---
#namespace specific service account for 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.saname }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.arn }}

---
#custom resource to fetch the secrets from paramter store
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.saname }}-aws-secrets
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data:
    - objectName: db_host
      key: DB_HOST
    - objectName: db_port
      key: DB_PORT
    - objectName: db_user
      key: DB_USER
    - objectName: db_password
      key: DB_PASSWORD
    # - objectName: db_database
    #   key: DB_DATABASE
    - objectName: db_schema
      key: DB_SCHEMA
    - objectName: redis_host
      key: REDIS_HOST
    - objectName: redis_port
      key: REDIS_PORT
    - objectName: redis_password
      key: REDIS_PASSWORD
    - objectName: redis_database
      key: REDIS_DATABASE
    - objectName: jwt_secret
      key: JWT_SECRET
    - objectName: jwt_issuer
      key: JWT_ISSUER
    - objectName: authentication_service_db_database
      key: AUTHENTICATION-SERVICE_DB_DATABASE
    - objectName: audit_service_db_database
      key: AUDIT-SERVICE_DB_DATABASE
    - objectName: notification_service_db_database
      key: NOTIFICATION-SERVICE_DB_DATABASE
    # - objectName: feature_toggle_service_db_database
    #   key: FEATURE-TOGGLE-SERVICE_DB_DATABASE
    - objectName: subscription_service_db_database
      key: SUBSCRIPTION-SERVICE_DB_DATABASE
    # - objectName: payment_service_db_database
    #   key: PAYMENT-SERVICE_DB_DATABASE
    - objectName: user_tenant_service_db_database
      key: USER-TENANT-SERVICE_DB_DATABASE
    - objectName: tenant_mgmt_service_db_database
      key: TENANT-MGMT-SERVICE_DB_DATABASE
    - objectName: cognito_domain_name
      key: COGNITO_AUTH_CLIENT_DOMAIN
    - objectName: cognito_client_id
      key: COGNITO_AUTH_CLIENT_ID
    - objectName: cognito_client_secret
      key: COGNITO_AUTH_CLIENT_SECRET
{{- if .Values.ses.enabled }}
    - objectName: ses_access_key
      key: SMTP_USER
    - objectName: ses_secret_access_key
      key: SMTP_PASSWORD
{{- end }}
  parameters:
#    region: us-west-2
    objects: |
      - objectName: {{ .Values.dbhost }}
        objectType: ssmparameter
        objectAlias: db_host
      - objectName: {{ .Values.dbport }}
        objectType: ssmparameter
        objectAlias: db_port
      - objectName: {{ .Values.dbuser }}
        objectType: ssmparameter
        objectAlias: db_user
      - objectName: {{ .Values.dbpassword }}
        objectType: ssmparameter
        objectAlias: db_password
      - objectName: {{ .Values.dbschema }}
        objectType: ssmparameter
        objectAlias: db_schema
      - objectName: {{ .Values.redishost }}
        objectType: ssmparameter
        objectAlias: redis_host
      - objectName: {{ .Values.redisport }}
        objectType: ssmparameter
        objectAlias: redis_port
      - objectName: {{ .Values.redispassword }}
        objectType: ssmparameter
        objectAlias: redis_password
      - objectName: {{ .Values.redisdatabase }}
        objectType: ssmparameter
        objectAlias: redis_database
      - objectName: {{ .Values.jwtsecret }}
        objectType: ssmparameter
        objectAlias: jwt_secret
      - objectName: {{ .Values.jwtissuer }}
        objectType: ssmparameter
        objectAlias: jwt_issuer
      - objectName: {{ .Values.authenticationdbdatabase }}
        objectType: ssmparameter
        objectAlias: authentication_service_db_database
      - objectName: {{ .Values.auditdbdatabase }}
        objectType: ssmparameter
        objectAlias: audit_service_db_database
      - objectName: {{ .Values.notificationdbdatabase }}
        objectType: ssmparameter
        objectAlias: notification_service_db_database
      - objectName: {{ .Values.subscriptiondbdatabase }}
        objectType: ssmparameter
        objectAlias: subscription_service_db_database
      - objectName: {{ .Values.userdbdatabase }}
        objectType: ssmparameter
        objectAlias: user_tenant_service_db_database
      - objectName: {{ .Values.tenantmgmtdbdatabase }}
        objectType: ssmparameter
        objectAlias: tenant_mgmt_service_db_database
      - objectName: {{ .Values.cognitodomain }}
        objectType: ssmparameter
        objectAlias: cognito_domain_name
      - objectName: {{ .Values.cognitoid }}
        objectType: ssmparameter
        objectAlias: cognito_client_id
      - objectName: {{ .Values.cognitosecret }}
        objectType: ssmparameter
        objectAlias: cognito_client_secret
{{- if .Values.ses.enabled }}
      - objectName: "/{{ .Values.projectName }}/ses_access_key"
        objectType: ssmparameter
        objectAlias: ses_access_key
      - objectName: "/{{ .Values.projectName }}/ses_secret_access_key"
        objectType: ssmparameter
        objectAlias: ses_secret_access_key
{{- end }}