---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: control-plane
  labels:
    app: {{ include "helm.name" . }}
spec:
  hosts:
    - {{ .Values.controlPlaneHost }}
  gateways:
    - control-plane 
  http:
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/authentication-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-authentication-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/audit-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-audit-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/notification-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-notification-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/subscription-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-subscription-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/tenant-mgmt-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-tenant-mgmt-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/tenant-mgmt-facade
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-tenant-mgmt-facade"
            port:
              number: 3000
    - match:
        - uri:
            prefix: {{ .Values.app.basePath }}/user-tenant-service
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-user-tenant-service"
            port:
              number: 3000
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "{{ include "helm.fullname" . }}-frontend"
            port:
              number: 80