apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.tier }}-{{ .Values.tenant }}
  labels:
    app: {{ include "helm.name" . }}
    Tenant: {{ .Values.tenant }} 
    Tenant_ID: {{ .Values.tenantID }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.hostname }}