region = "us-east-1"
environment = "dev"
namespace = "saas-demo"
github_connection_pipeline = "pipeline-conn"
github_FullRepositoryId    = "sourcefuse/terraform-aws-arc-eks-saas"
github_BranchName          = "feature/saas-demo"