region = "us-west-2"
environment = "dev"
namespace = "sf-arc-saas"
github_connection_pipeline = "pipeline-conn"
github_FullRepositoryId    = "sourcefuse/terraform-aws-arc-eks-saas"
github_BranchName          = "feature/saas-demo"