{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-cm-frontend
  labels:
    app: {{ include "helm.fullname" . }}
    Tenant: {{ .Values.tenant }} 
    Tenant_ID: {{ .Values.tenantID }}
data:
  env: |-
      {
        "baseApiUrl": "https://{{ .Values.hostname }}",
        "authServiceUrl": "{{ .Values.authenticationService.base_path }}",
        "userServiceUrl": "{{ .Values.userTenantService.base_path }}",
        "homePath": "{{ .Values.frontend.home_path }}",
        "logLevel": "{{ .Values.frontend.log_level }}",
        "clientId": "{{ .Values.clientId }}",
        "publicKey": "{{ .Values.publicKey }}"
      }
{{- end}}