{{- if .Values.videoConfrencingService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-cm-video-confrencing-service
  labels:
    app: {{ include "helm.fullname" . }}
    Tenant: {{ .Values.tenant }}
    Tenant_ID: {{ .Values.tenantID }}
data:
      PORT: '{{ .Values.videoConfrencingService.port }}'
      NODE_ENV: '{{ .Values.videoConfrencingService.node_env }}'
      LOG_LEVEL: '{{ .Values.videoConfrencingService.log_level }}'
      BASE_PATH: '{{ .Values.videoConfrencingService.base_path }}'
      DB_SSL: '{{ .Values.videoConfrencingService.db_ssl }}'
      VONAGE_API_KEY: '47793071'
      VONAGE_API_SECRET: 'f338183155d48b0fa0a1124f1d64459eaa917fda'
{{- end}}