---
#namespace specific service account for 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tier }}-{{ .Values.tenant }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.arn }}

---
#custom resource to fetch the secrets from paramter store
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.tier }}-{{ .Values.tenant }}-aws-secrets
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data:
    - objectName: db_host
      key: DB_HOST
    - objectName: db_port
      key: DB_PORT
    - objectName: db_user
      key: DB_USER
    - objectName: db_password
      key: DB_PASSWORD
    - objectName: db_schema
      key: DB_SCHEMA
    - objectName: redis_host
      key: REDIS_HOST
    - objectName: redis_port
      key: REDIS_PORT
    - objectName: redis_database
      key: REDIS_DATABASE
    - objectName: jwt_secret
      key: JWT_SECRET
    - objectName: jwt_issuer
      key: JWT_ISSUER
    - objectName: authentication_service_db_database
      key: AUTHENTICATION_SERVICE_DB_DATABASE
    - objectName: feature_db_database
      key: FEATURE_DB_DATABASE
    - objectName: notification_service_db_database
      key: NOTIFICATION_SERVICE_DB_DATABASE
    - objectName: video_confrencing_service_db_database
      key: VIDEO_CONFRENCING_SERVICE_DB_DATABASE
    - objectName: cognito_domain_name
      key: COGNITO_AUTH_CLIENT_DOMAIN
    - objectName: cognito_client_id
      key: COGNITO_AUTH_CLIENT_ID
    - objectName: cognito_client_secret
      key: COGNITO_AUTH_CLIENT_SECRET
  parameters:
#    region: us-west-2
    objects: |
      - objectName: {{ .Values.dbhost }}
        objectType: ssmparameter
        objectAlias: db_host
      - objectName: {{ .Values.dbport }}
        objectType: ssmparameter
        objectAlias: db_port
      - objectName: {{ .Values.dbuser }}
        objectType: ssmparameter
        objectAlias: db_user
      - objectName: {{ .Values.dbpassword }}
        objectType: ssmparameter
        objectAlias: db_password
      - objectName: {{ .Values.dbschema }}
        objectType: ssmparameter
        objectAlias: db_schema
      - objectName: {{ .Values.redishost }}
        objectType: ssmparameter
        objectAlias: redis_host
      - objectName: {{ .Values.redisport }}
        objectType: ssmparameter
        objectAlias: redis_port
      - objectName: {{ .Values.redisdatabase }}
        objectType: ssmparameter
        objectAlias: redis_database
      - objectName: {{ .Values.jwtsecret }}
        objectType: ssmparameter
        objectAlias: jwt_secret
      - objectName: {{ .Values.jwtissuer }}
        objectType: ssmparameter
        objectAlias: jwt_issuer
      - objectName: {{ .Values.authenticationdbdatabase }}
        objectType: ssmparameter
        objectAlias: authentication_service_db_database
      - objectName: {{ .Values.featuredbdatabase }}
        objectType: ssmparameter
        objectAlias: feature_db_database
      - objectName: {{ .Values.notificationdbdatabase }}
        objectType: ssmparameter
        objectAlias: notification_service_db_database
      - objectName: {{ .Values.videoconfrencingdbdatabase }}
        objectType: ssmparameter
        objectAlias: video_confrencing_service_db_database
      - objectName: {{ .Values.cognitodomain }}
        objectType: ssmparameter
        objectAlias: cognito_domain_name
      - objectName: {{ .Values.cognitoid }}
        objectType: ssmparameter
        objectAlias: cognito_client_id
      - objectName: {{ .Values.cognitosecret }}
        objectType: ssmparameter
        objectAlias: cognito_client_secret