---
name: Plan - Decoupling-Infratructure

on:
  push:
    branches:
      - feature/demo
  pull_request:
    branches:
      - dev
    paths:
      - 'terraform/decoupling-infra/*'
      - 'terraform/decoupling-infra/**'
      - '.github/workflows/plan-decoupling-infra.yaml'
      - '.github/workflows/reusable-ci-workflow.yaml'
  workflow_dispatch:

jobs:
  ## run terraform plan
  plan_dev:
    name: Decoupling-Infratructure
    uses: "./.github/workflows/reusable-ci-workflow.yaml"
    with:
      working_directory: decoupling-infra
      environment: dev
      assume_role_name: arc-saas-assume-role
      aws_region: us-west-2
      publish_plan_artifact: false  # only for apply step
      update_backend_config: true
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write